# Generated by Django 2.2.3 on 2019-07-22 10:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sendgrid', '0002_email_reason'),
    ]

    operations = [
        migrations.AlterIndexTogether(
            name='email',
            index_together=set(),
        ),
    ]
