# Generated by Django 3.2.20 on 2023-12-14 08:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sendgrid', '0004_alter_email_index_together'),
    ]

    operations = [
        migrations.AlterField(
            model_name='email',
            name='reason',
            field=models.TextField(default='', verbose_name='reason'),
        ),
    ]
